package com.inin.aiinterviewer.agent.model;

public enum QuestionQualityIssue {
    EMPTY_OR_UNCLEAR,
    STAGE_MISMATCH,
    COMPETENCY_MISMATCH,
    TARGET_MISMATCH,
    DUPLICATE_QUESTION,
    TOO_MANY_QUESTIONS,
    REFERENCE_ANSWER_LEAK,
    FABRICATED_CANDIDATE_CONTEXT,
    UNDECLARED_BACKGROUND,
    DIFFICULTY_MISMATCH,
    MEANINGLESS_PRESSURE,
    NOT_EVIDENCE_SEEKING
}
