package com.inin.aiinterviewer.domain.enums;

public enum LogicGapType {
    MISSING_BASELINE,
    MISSING_MECHANISM,
    MISSING_EXECUTION_PATH,
    MISSING_ALTERNATIVES,
    MISSING_TRADE_OFF,
    MISSING_VALIDATION,
    MISSING_PERSONAL_CONTRIBUTION,
    MISSING_FAILURE_HANDLING,
    CAUSALITY_JUMP,
    RESULT_WITHOUT_EVIDENCE
}
