package com.inin.aiinterviewer.domain.enums;

public enum ProbeStrategy {
    CLARIFY_CONCEPT,
    REQUEST_BASELINE,
    REQUEST_METRIC_BREAKDOWN,
    VERIFY_PERSONAL_OWNERSHIP,
    VERIFY_DATA_SOURCE,
    TRACE_CAUSAL_CHAIN,
    ASK_IMPLEMENTATION_DETAIL,
    ASK_TRADE_OFF,
    ASK_ALTERNATIVE,
    INTRODUCE_CONSTRAINT,
    INTRODUCE_FAILURE,
    CROSS_CHECK_HISTORY,
    CHALLENGE_ASSUMPTION,
    REQUEST_PRIORITIZATION
}
